### ISSUE TITLE
Add api.gsa.gov in front of this

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/prototype-city-pairs-api#36]
Demonstrate API standards by implementing api.gsa.gov.

Need to determine how we can do this and not give false impression that this is a production API. (Currently no sandbox environment exists for api.gsa.gov).

**Comment by jfredrickson5** [comment]
A few ideas:

Use a hostname that emphasizes it is a demo (demo-api.gsa.gov; demo.api.gsa.gov)

On the documentation page, if you're using USWDS, use the banner feature to state that it is a demo site.

Use USWDS warning alert box at the top of the documentation content to emphasize that it is a demo.

**Comment by gbinal** [comment]
Hmmm....  My suggestion would be just to focus on making that clear in the documentation and not to worry about the URL.  

@rdgsa - I can api.gsa.gov set up in front of this in about 2 minutes if you're game.  It won't be published anywhere and you can play around with it and get a feel for the benefits of it before updating your documentation with the `api.gsa.gov` URL.  

My suggestion though is to let me go ahead and do this and to go ahead and update the documentation b/c in the meantime, you don't have good API analytics in place to know if anyone is using the API and with this you then would. 

If you're game, give me a 👍  anytime and I'll get that to you.  

You can set up a `demo-api.gsa.gov` domain and it would then be available for things like this, though you'll need to put in a new DNS request and it'll take a while to get in place.

**Comment by Ryandaydev** [comment]
@jcastle Let's talk about this in our transition meetings.

**Comment by Ryandaydev** [comment]
Just wanted to make a note that I have updated the doco to emphasis it is a prototype only.

**Comment by Ryandaydev** [comment]
@gbinal we've received the all-clear to put api.gsa.gov in front of this.

A few ways we have marked this as a prototype:
- API documentation includes "Prototype" in the title.
- API documentation includes the following statement `"It is not a production API, and it is not intended for use by the public."`
- API version is "V0"
- Response object contains a message `"This is a prototype API. These results are for demonstration purposes only."` in the payload.
- URL path includes the word "prototype"

**Comment by gbinal** [comment]
Heyyy!!!!  That's great news.   Yeah, I mean I think, that's 2-3x overkill, but whatever floats your boat.  

Alright - this is ready.  

`https://citypairsprototypeapi.app.cloud.gov/travel/citypairs/v0/airfares` => `https://api.gsa.gov/systems/citypair/airfares`

For example:  

https://citypairsprototypeapi.app.cloud.gov/travel/citypairs/v0/airfares?award_year=2015&origin_airport_abbrev=abq&destination_airport_abbrev=BWI

==> 

https://api.gsa.gov/systems/citypair/airfares?award_year=2015&origin_airport_abbrev=abq&destination_airport_abbrev=BWI&api_key=DEMO_KEY1

Ryan, you should have access the analytics for this API at api.data.gov/admin.  Feel free to hit us up at api.data.gov@gsa.gov to let me know who else should have access or to ask any questions.

**Comment by Ryandaydev** [comment]
This has been implemented. New URL path:

https://api.gsa.gov/travel/citypairs/v0/airfares/99?api_key=DEMO_KEY
